<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>Pager.Duty.Webhooks</RootNamespace>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <IncludeSource>true</IncludeSource>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);IDE0290;CS8509</NoWarn>

        <Version>$(ProjectVersion)</Version>
        <Description>Receive PagerDuty incident updates by receiving Webhooks V3 requests using ASP.NET Core.</Description>
        <Authors>Ben Hutchison</Authors>
        <Company>$(Authors)</Company>
        <Copyright>© 2026 $(Authors)</Copyright>
        <PackageTags>pagerduty webhook</PackageTags>
        <PackageProjectUrl>https://github.com/Aldaviva/PagerDuty</PackageProjectUrl>
        <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
        <PackageReleaseNotes>$(PackageProjectUrl)/releases/tag/$(Version)</PackageReleaseNotes>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <WarningsAsErrors>$(WarningsAsErrors);CA1859</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="..\PagerDuty\ExceptionAdjustments.txt" />
        <InternalsVisibleTo Include="Tests;Test.Webhooks" />
        <None Include="..\PagerDuty\icon.png;..\Readme.md" Pack="true" PackagePath="\" />
        <None Include="..\.github*\**" Visible="true" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="[10.0.112,10.0.200)" PrivateAssets="All" />
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <Choose>
        <When Condition="'$(Configuration)' != 'Debug'">
            <ItemGroup>
                <PackageReference Include="PagerDuty" Version="$(ProjectVersion)" />
            </ItemGroup>
        </When>
        <Otherwise>
            <ItemGroup>
                <ProjectReference Include="..\PagerDuty\PagerDuty.csproj" />
            </ItemGroup>
        </Otherwise>
    </Choose>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' or '$(Configuration)' != 'Debug'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

</Project>