name: .NET

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: PagerDuty

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Initialize test reporting
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}

    - name: Set up
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
        
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: |
        dotnet test --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --settings Tests/coverlet.runsettings --logger trx
        Out-File -InputObject "TEST_EXIT_CODE=$LASTEXITCODE" -FilePath $env:GITHUB_ENV -Append -Encoding UTF8
        Get-ChildItem Tests\TestResults\*\coverage.info | Rename-Item -NewName lcov.info
        exit 0

    - name: Pack
      run: dotnet pack ${{ env.ProjectName }} --no-build --configuration Release

    - name: Upload test report
      run: testspace Tests/TestResults/*.trx

    - name: Upload coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Stop if tests failed
      run: exit $env:TEST_EXIT_CODE

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ProjectName }}.nupkg
        path: ${{ env.ProjectName }}/bin/Release/*.*nupkg